### PR TITLE
Unsorted require statements cause problems on some platforms

### PR DESCRIPTION
**Pull request by alexkwolfe**
Discovered this today when I used your gem on an older Ubuntu system.  Sorting the Dir glob array fixed the problem.

### CODE REVIEW

**Comment by ramaboo** [comment]
I can confirm that this is an issue on Ubuntu and that the above fix works. Thanks. I was getting uninitialized constant errors when using this without this fix. I will send Michael and email and see if we can get this pulled in and a new gem created.

**Comment by joshnabbott** [comment]
I'll +1 this. Getting "Uninitialized constant 'uninitialized constant Zferral::Resource' on ubuntu.

**Comment by ramaboo** [comment]
Any chance we can get a fix soon on this. Every time I rebuild my gems I have to manually fix this gem.

**Comment by shayfrendt** [comment]
Hey guys - I just ran into this same issue.  Didn't realize this repo was still hanging out off the grasshopperlabs GitHub account.  I'm looking into this and will try to get it merged in shortly.

**Comment by shayfrendt** [comment]
FYI: Just released zferral version 0.2.2 to rubygems.

**Pull request merged**
